### PR TITLE
feat: add new web socket for parameters

### PR DESCRIPTION
**Pull request by kaualandi**
I've made considerable progress on the numerical parameters, and I apologize for the delay, but reconciling work and this project hasn't been easy. I've listed below and commented out in the code what should be used in this new websocket to receive the parameters.

I don't think it's necessary to use canvas for these values. I'm not that experienced in canvas, but I think it's more complicated when it comes to responsiveness (I could be wrong).

param.channel is the channel name
param.value is the value of the parameter
Some of the fields have minimum and maximum values, which must be specified in the bottom left-hand corner, as in the printout below.
These values are located at:
Min: param.alarm.min
Max: param.alarm.max
Some fields do not have the “alarm” object, so this must be dealt with.

Captura de Tela 2024-05-27 às 10 45 29

### CODE REVIEW

**Review by smappaa — APPROVED** [review]

**Comment by smappaa** [comment]
Excellent job! I'll start working on this. So the param.value is a number, which currently updates about every 35 seconds. I think I will approach this by just displaying the latest value until/if there is an updated value to replace it with.

I believe we can achieve the needed responsiveness with just using canvas, but we have to define what is the right sizing for the elements of the user interface. The right sizing probably changes between different types of displays, and also depends on the use case. For example, on a mobile phone we could need bigger scaling just to be able to comfortably view everything (especially while moving), but at the same time it could be perfect on a laptop screen with same resolution and less PPI.

**Comment by kaualandi** [comment]
I believe that from a certain resolution, we could place the parameters below or above the curves, and remove them from the side.

**Comment by smappaa** [comment]
Now many of the important parameters are drawn. I also limited the amount of views to 3 for now, as there are usually not that many needed at the same time. Only one ECG signal is being displayed by default. I also added a feature where you can click/supposedly touch a view to change it; clicking it will open a menu with the options to switch that view to another one that is not currently displayed. For now, I didn't do much for the sake of responsiveness, although these changes kind of play into that goal in my opinion. Tell me what you think of the things I came up with, and the "responsiveness" of the interface. :)

**Comment by kaualandi** [comment]
Forgive me for taking so long, it's really very good, but showing all the curves returned is a very important factor. By the way, the endpoint has changed and I don't think I've been able to do any more tests because of that. I'll send you the new IP address:

ws://139.82.24.175:8002/

**Pull request merged**
