### PR TITLE
feat: add websocket connection

### PR DESCRIPTION
**Pull request by kaualandi**
Implementing the real websocket, at the time of testing, I was only receiving the ecg_i, but that wasn't a problem.

I believe I have implemented it correctly, let me know if I'm wrong, but the curve seems to me to be mirrored.

Here you can see the curve coming from the websocket in your implementation:
Captura de Tela 2024-05-07 às 08 47 16

And here's the one I rendered with Microsoft Excel:
Captura de Tela 2024-05-07 às 08 52 51

In addition, we'll have to make some sort of garbage collector, because if the curves object is never emptied, there will come a time when we'll have memory leaks, as I believe has happened here:
Captura de Tela 2024-05-07 às 08 49 17

Anyway, thank you very much for your effort, and I've left the ip of the websocket in the code so you can do more tests.

### CODE REVIEW

**Comment by smappaa** [comment]
Hello! I just pushed changes which should help in eliminating the issues we were experiencing.

First off, I flipped the data points so that the signal is drawn upside down, assuming that the data points should be read from the bottom of the display and not top as before.

Secondly, I worked towards fixing the logic of timing in the code, so to speak. The problems that you witnessed with the data not being drawn were - to my understanding - not about memory management, because in the code the data arrays are continuously overwritten.

The signal seems to be drawn continuously and correctly now, even for longer times. Still, sometimes you will see that there are slight breaks in the drawn data, which is due to minimal or nonexistent buffer time between the websocket messages. And rarely, there's a whole message missing, which results in a delay of >5000ms.

In theory, the small breaks could be fixed with adding a slight delay (100-500 ms) after receiving first message, so that there's always new data ready waiting to follow up the previous. However, this won't fix it for longer streaming durations due to a growing time gap between the messages received from the websocket. See these pictures of what I witnessed:

100msgdelay
In the first picture you can see that the average delay of the last 100 messages received is 5066 ms, which means these packages are not back to back.
200msgdelay
Here you will see that the delay closes in slightly over longer periods.

10000msdelay
In this picture you can see that there's a whole message missing.

I also noticed that some messages would have 1536 or 1024 data points instead of the usual 1280, which was unexpected. You could then assume that a message with more data points would mean longer duration between the messages start_date and end_date. However, this was not the case; the "data duration" would still be 5000 ms. See these pictures:


Message with 1536 data points.

Message with 1024 data points.

As the code bases its message draw duration on the messages time stamps - not the amount its data points - this results, for example, in a visual increase of the heart rate with a package having > 1280 data points per 5000 ms. Naturally the effect is the opposite for a package having less data points per 5000 ms.

I don't have answers to these phenomena. I just wanted to let you know about these observations, in case this information is beneficial to you, knowing that you provided me with the websocket data. And naturally this will affect what you see on the display.

All in all, than you very much for this collaboration! I am satisfied with the results and I am open to further discussions and possible changes. Check out the repository, and also see the developer console as I left some debug code in place.

**Comment by kaualandi** [comment]
Thank you for all the comments. They are all relevant. I will try to explain some issues to make it clearer for you.
Start_date and End_date represent the start and end of the time I collect the information sent by the device. However, the hardware itself can sometimes delay by a few milliseconds, in addition to network latency, which can also influence on a smaller scale.
The packets arrive in sizes that are multiples of 256 data points. Collecting for 5 seconds, I have 1280 data points. If there is a delay, the packet may contain 1024 data points, which represents only 4 seconds x 256 data points. When the packet has 1536 data points, it should represent 6 seconds and probably it will arrive some time before or after a 1024 data points packet.
The most important thing is to know that 256 data points represent 1 second and that factors beyond our control can make the size of the received data packet vary slightly more or less. To solve such a problem, we might need to have a slightly larger buffer, what do you think about it?

**Comment by smappaa** [comment]
Thank you for the information! I think the first thing we should do is change the logic so that the client side code assumes 1 second to always be 256 points, whatever the data point amount and end_date - start_date of the message are. This will help with displaying the data in the right time span and fix the false changes in heart rate.

I'm not sure I know how you would approach the buffer issue. Do I understand this right, that even though the average time between messages is ~5050 ms there are enough messages with extra 256 data points to compensate this? If this is the case, adding a slight drawing start delay on the client side after receiving first message should help with solving the buffer issues, together with the change in the logic I suggested in the first paragraph.

**Comment by kaualandi** [comment]
Adding a small delay at the start of the drawing on the client side after receiving the first message I believe is the ideal solution, but care must be taken not to exceed 10 seconds, I believe that leaving one accumulated buffer is enough.

I'd like to propose something else, to have all the curves displayed at the same time.
I can see if I can get the monitor to also return other data that isn't curves, as shown on the right side of the monitor below, I think that would give an interesting result. I'll work on it and get back to you so we can try something:

162739-800-auto

**Comment by smappaa** [comment]
All right, let's put the delay in place. I was also thinking the delay shouldn't exceed the interval of 2 messages, so a 5 second delay should be more than enough, and probably more than needed. We want to make this as real time as possible. If we want to optimize this further in the future we could change the data gathering period to 2-3 seconds (from 5 s), and the delay to 2-3 seconds respectively, which would then put us at 4-6 seconds delay... and keep lowering the numbers until it's technically impossible. But that's not the main thing right now, and we would have to dive deeper into the details there.

I like your proposal, we can definitely work towards making this an actual interface with various information. I'm really looking forward to seeing what we can make out of this!

I'll start working on the changes and work towards displaying multiple ECG views on top of each other, and the option to display numbers on the right side of the drawn signal.

**Comment by smappaa** [comment]
Okay, I got some results for you to see here! I redesigned the interface to accommodate only the drawn ECG views on top of each other. I also changed the data handling logic so that it's always 256 points per second, disregarding start_date and end_date altogether. I put in the drawing start delay, its 3000 ms right now and it seems to be working well. There was also a small bug I was unaware of, that caused the drawn signal to break for one frame every time the data was swapped, so that's fixed as well. A lot if not all of the lag with data receiving and handling seems to be fixed now.

**Comment by kaualandi** [comment]
This is getting more and more incredible, I'm finalizing the numerical data and will soon open PR so you can help me with this frontend work. The idea is for the interface to be responsive too, I think that appearing on mobile devices would be interesting

**Pull request merged**
